import 'package:flutter/material.dart';
import 'package:turisr/classes/estabelecimento.dart';

class LocaisRepository extends ChangeNotifier {
  final List<Estabelecimento> locais = [
    Estabelecimento(
      id: 5,
      nome: "Vinícola Goes",
      caminhoImagem: "assets/imagens/vinicola_goes.jpg",
      descricao:
          "Fundada na d\u00e9cada de 1910 e comercializada nos anos 1980, a Vin\u00edcola Goes \u00e9 refer\u00eancia em S\u00e3o Roque. Com produ\u00e7\u00e3o anual de at\u00e9 10 milh\u00f5es de litros, oferece visitas guiadas, lojas, gastronomia variada e um belo lago. Um espa\u00e7o encantador que proporciona experi\u00eancias memor\u00e1veis para todas as idades.",
      rua: "Estrada do Vinho, Km 9, S\u00e3o Roque-SP",
      numero: 9111,
      servicos: List.empty(),
      latitude: -23.610702,
      longitude: -47.160289,
      notaAvaliacao: 5,
      tipo: 'E',
    ),
    Estabelecimento(
      id: 6,
      nome: "Restaurante Pica-Fumo",
      caminhoImagem: "assets/imagens/restaurante_pica-fumo.jpg",
      descricao:
          "Localizado no km 1,5 do Roteiro do Vinho, o restaurante encanta pelo ambiente acolhedor e culin\u00e1ria caipira feita no fog\u00e3o \u00e0 lenha. Com estacionamento, espa\u00e7o ao ar livre e pratos t\u00edpicos como feijoada aos s\u00e1bados, resgata tradi\u00e7\u00f5es brasileiras e oferece uma experi\u00eancia deliciosa e aut\u00eantica.",
      rua: "Estrada do Vinho, Km 1,5, S\u00e3o Roque-SP",
      numero: 177,
      latitude: -23.558666,
      longitude: -47.128581,
      servicos: List.empty(),
      notaAvaliacao: 4,
      tipo: 'E',
    ),
    Estabelecimento(
      id: 7,
      nome: "Divina Cantina",
      caminhoImagem: "assets/imagens/divina_cantina.jpg",
      descricao:
          "Oferece um buffet \u00e0 vontade com pratos caseiros e caf\u00e9 colonial em um ambiente acolhedor e r\u00fastico. Ideal para quem busca sabores aut\u00eanticos e um come\u00e7o de dia delicioso na charmosa Rota do Vinho em S\u00e3o Roque.",
      rua: "Rua Dr. Durval Villa\u00e7a, Jardim Villaca",
      numero: 517,
      latitude: -23.550619,
      longitude: -47.123478,
      servicos: List.empty(),
      notaAvaliacao: 4,
      tipo: 'E',
    ),
    Estabelecimento(
      id: 8,
      nome: "Villa don Patto",
      caminhoImagem: "assets/imagens/villa_don_patto.jpg",
      descricao:
          "Um complexo enogastron\u00f4mico com culin\u00e1ria portuguesa e italiana, adega, emp\u00f3rio, sorveteria e belas paisagens. O espa\u00e7o conta com \u00e1rea de lazer, playground e mirantes, sendo um passeio completo para todas as idades.",
      rua: "Estrada do Vinho Km 2,5, Jardim Villaca",
      numero: 0,
      latitude: -23.563481,
      longitude: -47.135612,
      servicos: List.empty(),
      notaAvaliacao: 5,
      tipo: 'E',
    ),
    Estabelecimento(
      id: 9,
      nome: "Vin\u00edcola XV de Novembro",
      caminhoImagem: "assets/imagens/vinicola_novembro.jpg",
      descricao:
          "Desde 1958, preserva a tradi\u00e7\u00e3o na produ\u00e7\u00e3o de vinhos, sucos e espumantes artesanais. Oferece degusta\u00e7\u00f5es, loja pr\u00f3pria, piqueniques e contato com a natureza, com vistas encantadoras da Mata Atl\u00e2ntica.",
      rua: "Estrada Achiles Augusto de Moraes, Sorocamirim",
      numero: 500,
      latitude: -23.583233,
      longitude: -47.142257,
      servicos: List.empty(),
      notaAvaliacao: 3,
      tipo: 'E',
    ),
    Estabelecimento(
      id: 10,
      nome: "Quinta do Olivardo",
      caminhoImagem: "assets/imagens/quinta_olivardo.jpg",
      descricao:
          "Comida t\u00edpica portuguesa, vinhos artesanais, pedalinho no lago, tirolesa, \u00e1rea kids e eventos sazonais fazem da Quinta uma experi\u00eancia cultural e gastron\u00f4mica \u00fanica, que encanta fam\u00edlias e visitantes de todas as idades.",
      rua: "Estrada do Vinho, Km 5.7, Sorocamirim",
      numero: 77,
      latitude: -23.576688,
      longitude: -47.139178,
      servicos: List.empty(),
      notaAvaliacao: 3,
      tipo: 'E',
    ),
    Estabelecimento(
      id: 11,
      nome: "Caracol Chocolates",
      caminhoImagem: "assets/imagens/caracol_chocolates.jpg",
      descricao:
          "Unidade da tradicional chocolateria de Gramado. Oferece chocolates artesanais, mini fondue, cafeteria, waffles e ambiente l\u00fadico, que conquista tanto os f\u00e3s de chocolate quanto fam\u00edlias com crian\u00e7as pequenas.",
      rua: "Estrada do Vinho, Km 1, Gabriel Piza",
      numero: 400,
      latitude: -23.557397,
      longitude: -47.126712,
      servicos: List.empty(),
      notaAvaliacao: 4,
      tipo: 'E',
    ),
    Estabelecimento(
      id: 12,
      nome: "Emp\u00f3rio QN",
      caminhoImagem: "assets/imagens/emporioqn.jpg",
      descricao:
          "Espa\u00e7o moderno com wine bar, vinhos da casa, r\u00f3tulos nacionais e importados, drinks artesanais, embutidos e ambiente instagram\u00e1vel. Uma experi\u00eancia descontra\u00edda e elegante para quem curte degustar e relaxar.",
      rua: "Rua Durval Villa\u00e7a, Jardim Villa\u00e7a",
      numero: 557,
      latitude: -23.551509,
      longitude: -47.123387,
      servicos: List.empty(),
      notaAvaliacao: 4,
      tipo: 'E',
    ),
    Estabelecimento(
      id: 13,
      nome: "Museu do Vinho",
      caminhoImagem: "assets/imagens/emporioqn.jpg",
      descricao:
          "Espaço dedicado à história vitivinícola de São Roque, com acervo de ferramentas, rótulos e equipamentos antigos. Oferece exposições temáticas e loja de vinhos locais, sendo parada obrigatória na Rota do Vinho.",
      rua: "Rua São Judas Tadeu, Gabriel Piza",
      numero: 1183,
      latitude: -23.5596561856438,
      longitude: -47.12138447639987,
      servicos: List.empty(),
      notaAvaliacao: 4,
      tipo: 'P',
    ),
    Estabelecimento(
      id: 14,
      nome: "Capela Santo Antônio",
      caminhoImagem: "assets/imagens/capela_santo_antonio.jpg",
      descricao:
          "Construída em 1682 por Fernão Paes de Barros, é um dos mais antigos patrimônios de São Roque. Feita em taipa de pilão, com torre de pedra e fachada em madeira, integra o Sítio Santo Antônio. Cercada por natureza, encanta pela arquitetura jesuítica.",
      rua: "Estrada Mário de Andrade",
      numero: 8,
      latitude: -23.5010941741441,
      longitude: -47.08909053982698,
      servicos: List.empty(),
      notaAvaliacao: 4,
      tipo: 'P',
    ),
  ];
}
