// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBy3TgtPxj6OMQnuWBLEc10xFrOR_KFog',
    appId: '1:265181860609:web:a9f61c1f246f77914d0100',
    messagingSenderId: '265181860609',
    projectId: 'projeto-login-6ff78',
    authDomain: 'projeto-login-6ff78.firebaseapp.com',
    storageBucket: 'projeto-login-6ff78.firebasestorage.app',
    measurementId: 'G-W0NW1G006M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwn-Qi1c7q9JDUWWD5Tx5zRWgKcni8GoM',
    appId: '1:265181860609:android:f1f1ba20d409241b4d0100',
    messagingSenderId: '265181860609',
    projectId: 'projeto-login-6ff78',
    storageBucket: 'projeto-login-6ff78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUw7dnTwGaAo8icIanDfY3d_ojHHeVZoA',
    appId: '1:265181860609:ios:6de81943188d11d34d0100',
    messagingSenderId: '265181860609',
    projectId: 'projeto-login-6ff78',
    storageBucket: 'projeto-login-6ff78.firebasestorage.app',
    iosBundleId: 'com.example.turiSr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUw7dnTwGaAo8icIanDfY3d_ojHHeVZoA',
    appId: '1:265181860609:ios:6de81943188d11d34d0100',
    messagingSenderId: '265181860609',
    projectId: 'projeto-login-6ff78',
    storageBucket: 'projeto-login-6ff78.firebasestorage.app',
    iosBundleId: 'com.example.turiSr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBy3TgtPxj6OMQnuWBLEc10xFrOR_KFog',
    appId: '1:265181860609:web:db849bfa06ade2914d0100',
    messagingSenderId: '265181860609',
    projectId: 'projeto-login-6ff78',
    authDomain: 'projeto-login-6ff78.firebaseapp.com',
    storageBucket: 'projeto-login-6ff78.firebasestorage.app',
    measurementId: 'G-S03ETJECE8',
  );
}
